path: /mnt/f/datasets/new_label_v1.0/v1.3
# path: D:/code/yolo/dataset_balanced_mixed
# path: D:/code/yolo/dataset_balanced_overc
train: images/train
val: images/val
# test: images/test  
names:
  0: airflow_print
  1: broken_batch
  2: broken_deep
  3: broken_single
  4: claw
  5: claw_discrete
  6: concentric_circles
  7: crack
  8: crack_x
  9: dirty
  10: dot
  11: dot_batch
  12: edge_black
  13: misty_stripe
  14: offset
  15: scratch
  16: shading_black
  17: shading_edge
  18: suction_print
  19: water_print